### ISSUE TITLE
Crash when opening config screen

### ISSUE THREAD

**Issue by sylv256** [Siphalor/wandering-collector#3]
# Description
When I open the configuration screen, the game crashes.

# Reproduction
1. Open "Mods" menu
2. Find and select "Wandering Collector"
3. Select the "Configure" button
4. Crash!

# Versions
Minecraft | Mod | Loader | FAPI | JVM | OS
--------- | --- | ------ | ---- | --- | --
`1.17.1` | `1.02+mc1.17` | `0.12.1` | `0.40.6+1.17` | `adoptopenjdk-16-hotspot-jre-amd64` | `Ubuntu 20.04`

# JVM Arguments
```
-XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:ConcGCThreads=8 -XX:+ZUncommit -XX:+UseCompressedClassPointers -XX:+UseCompressedOops
```

# Log
https://paste.ee/p/qYMWf

**Comment by thcrt** [comment]
I'm also experiencing this in 1.19.4. 

https://bytebin.lucko.me/tSwMjT49s9
