### ISSUE TITLE
Latest update causes a crash

### ISSUE THREAD

**Issue by HYPExMon5ter** [Siphalor/wandering-collector#6]
I'm running Fabric 0.12.12 and the last update of Wandering Collector for 1.18 (version 1.1.0) is causing a crash.
here's my [latest.log](https://github.com/Siphalor/wandering-collector/files/7937165/latest.log)

**Comment by Siphalor** [comment]
That's what happens if one doesn't do proper testing on all Minecraft versions :P

Thanks for reporting, this should:tm: be fixed now in version 1.1.1 (commit 6fe34d48653dcb7a57d3067227c796002df624f5).
