### ISSUE TITLE
Update to 1.18.2 

### ISSUE THREAD

**Issue by Aulluna** [Siphalor/wandering-collector#7]
I dont know the mod is breaking in 1.18.2 , it shouldnt do that since the versio is supposed to only change technical stuffs related to worldgen . still Can u pls find the issue and fix it ? 
( note the error log that pops up into my server log , is very very similar to Nullscape 1.1 error when i tried to run it on 1.18.2 )

**Comment by Siphalor** [comment]
done :)

1.18.2 had also some changes to how Minecraft is handling tags, that caused the incompaitbiliy.

**Comment by Aulluna** [comment]
thx alot
it is good , but sad at the same moment , I wanted to post this
![image](https://user-images.githubusercontent.com/76559595/159363170-c7b4ece9-87ef-49a8-8e38-60c9074d072d.png)
